# Generated by Django 5.1.4 on 2025-01-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(help_text='Temperature in degrees')),
                ('humidity', models.IntegerField(help_text='Humidity percentage')),
                ('clouds', models.CharField(help_text='Cloud description', max_length=255)),
                ('speed', models.FloatField(help_text='Wind speed in m/s')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of data recording')),
            ],
        ),
    ]
