# Generated by Django 5.1.4 on 2025-01-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
