# Generated by Django 5.1.4 on 2025-01-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0002_weather_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='description',
            field=models.CharField(default='Unknown', max_length=500),
        ),
    ]
