# Generated by Django 5.1.4 on 2025-01-13 04:45

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0003_weather_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weather',
            name='clouds',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weather',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='recorded_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='speed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temp',
            field=models.FloatField(),
        ),
        migrations.AddConstraint(
            model_name='weather',
            constraint=models.UniqueConstraint(condition=models.Q(('recorded_at', django.db.models.functions.datetime.TruncDate('recorded_at'))), fields=('city',), name='unique_city_date'),
        ),
    ]
